### ISSUE TITLE
/api/search with_node_links

### ISSUE THREAD

**Issue by walk1ndude** [RedForester/python_rf_api_client#9]
https://github.com/RedForester/python_rf_api_client/blob/eb9dc690e7442bbbfd541a2e6f37cf80013edfbc/rf_api_client/api/maps_api.py#L87

Why no `with_node_links` here?

**Comment by strangecamelcaselogin** [comment]
https://github.com/RedForester/python_rf_api_client/commit/2bb4e9bf4a5aa530716a0cd0053db89bc46e5d96

Also https://github.com/RedForester/python_rf_api_client/commit/160f5e85185ecae05d619ceb41154b8533b9c1a6 and https://github.com/RedForester/python_rf_api_client/commit/93131d229f2246b10ebd842bda921b2011b41beb might be useful
